### ISSUE TITLE
Problem with loading Meower Beta 5 on TurboWarp

### ISSUE THREAD

**Issue by Marc92020** [meower-media-co/Meower-Vanilla-Beta#1]
I can't load Meower Beta 5.0 on TurboWarp
![help](https://user-images.githubusercontent.com/75702334/150696886-24d05a9d-d47c-4f1b-b1af-d2baae17fc92.png)

**Comment by Melt2002** [comment]
Do you use Chrome (or a chrome based browser, such as Brave, Edge, Vivaldi), Safari, or Firefox?

**Comment by MikeDev101** [comment]
show me a screenshot of your inspect console.

**Comment by Mwalters75** [comment]
Did you follow the instructions on: https://github.com/meower-media-co/Meower-Vanilla-Beta#note-to-get-the-beta-5-source-code-to-load-correctly-you-will-need-to-have-the-cloudlink-turbo-extension-js-injected-into-the-editor-you-can-simply-get-a-js-injector-extension-for-your-browser-and-add-this-files-contents-as-a-rule-for-turbowarporg? (It says that you need CloudLink TURBO for it to load correctly, and will not load, if you don't specify it in the URL, or in the "Choose a Block" menu)

**Comment by Bloctans** [comment]
needs cloudlink turbo.

**Comment by Melt2002** [comment]
Bloctans? This hasn't been resolved, and they had said they are using it.

**Comment by Melt2002** [comment]
(IIRC of course, think they said it on meower a bit back)

**Comment by Marc92020** [comment]
> Do you use Chrome (or a chrome based browser, such as Brave, Edge, Vivaldi), Safari, or Firefox?
> 
> Easier way to say it: What browser do you use?

i use chrome


> show me a screenshot of your inspect console.

![Screenshot 2022-01-26 180812](https://user-images.githubusercontent.com/75702334/151262321-95140b14-0e35-4ff1-8a8e-bcdbb929bfc5.png)


> Did you follow the instructions on: https://github.com/meower-media-co/Meower-Vanilla-Beta#note-to-get-the-beta-5-source-code-to-load-correctly-you-will-need-to-have-the-cloudlink-turbo-extension-js-injected-into-the-editor-you-can-simply-get-a-js-injector-extension-for-your-browser-and-add-this-files-contents-as-a-rule-for-turbowarporg? (It says that you need CloudLink TURBO for it to load correctly, and will not load, if you don't specify it in the URL, or in the "Choose a Block" menu)

yes

**Comment by MikeDev101** [comment]
> 

Now just do that but select "console" in that menu

**Comment by Marc92020** [comment]
> > 
> 
> Now just do that but select "console" in that menu

well i found something interesting
![Screenshot 2022-01-27 204042](https://user-images.githubusercontent.com/75702334/151472306-58eab61b-d2d7-489f-9343-7c1d5a6525dd.png)

**Comment by Marc92020** [comment]
> > > 
> > 
> > 
> > Now just do that but select "console" in that menu
> 
> well i found something interesting ![Screenshot 2022-01-27 204042](https://user-images.githubusercontent.com/75702334/151472306-58eab61b-d2d7-489f-9343-7c1d5a6525dd.png)

i think these are turbowarp errors though
