### ISSUE TITLE
beta.meower.org's certificate expired today

### ISSUE THREAD

**Issue by Mwalters75** [meower-media-co/Meower-Vanilla-Beta#2]
![Screenshot 2022-01-23 8 05 42 PM](https://user-images.githubusercontent.com/67456566/150706539-9b877691-3d26-46a3-a4f1-a86a452910df.png)
Isn't today the 23<sup>rd</sup>?

**Comment by Melt2002** [comment]
Everything seems fine. If it becomes an issue, me or someone else will contact Cloudflare and get it resolved.

**Comment by MikeDev101** [comment]
that says it was created the 22 of this year, and expires on the 23 of NEXT year.

**Comment by Melt2002** [comment]
LOL, I didn't even notice that. If I'm correct, it should automatically renew though.
